/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { UsageProgress, UsageSnapshot } from '@deepseek-ai/dsh-client-ui-usage/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$757361676553746174697374696373 {
    progress: () => Promise<RemoteResult<UsageProgress>>
    snapshot: (force: boolean) => Promise<RemoteResult<UsageSnapshot>>
  }
  interface TypertRemoteMap {
    'usageStatistics/progress': () => Promise<RemoteResult<UsageProgress>>
    'usageStatistics/snapshot': (force: boolean) => Promise<RemoteResult<UsageSnapshot>>
  }
  interface TypertRemoteNamespaceMap {
    'usageStatistics': TypertRemoteNamespace$757361676553746174697374696373
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
