/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

let _deepseek_ai_dsh_client_ui_usage_usageStatistics_progress_result$schema$value
const _deepseek_ai_dsh_client_ui_usage_usageStatistics_progress_result$schema = () => (_deepseek_ai_dsh_client_ui_usage_usageStatistics_progress_result$schema$value ??= z.object({
  'completed': z.number().readonly(),
  'total': z.number().readonly(),
  'running': z.boolean().readonly(),
}))
let _deepseek_ai_dsh_client_ui_usage_usageStatistics_snapshot_parameter_0$schema$value
const _deepseek_ai_dsh_client_ui_usage_usageStatistics_snapshot_parameter_0$schema = () => (_deepseek_ai_dsh_client_ui_usage_usageStatistics_snapshot_parameter_0$schema$value ??= z.boolean())
let _deepseek_ai_dsh_client_ui_usage_usageStatistics_snapshot_result$schema$value
const _deepseek_ai_dsh_client_ui_usage_usageStatistics_snapshot_result$schema = () => (_deepseek_ai_dsh_client_ui_usage_usageStatistics_snapshot_result$schema$value ??= z.object({
  'capturedAt': z.number().readonly(),
  'projects': z.array(z.object({
  'id': z.string().readonly(),
  'title': z.string().readonly(),
})).readonly(),
  'sessions': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'projectId': z.string().readonly().optional(),
  'lastAt': z.number().readonly(),
  'missingTurns': z.number().readonly(),
})).readonly(),
  'records': z.array(z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'at': z.number().readonly(),
  'inputTokens': z.number().readonly(),
  'outputTokens': z.number().readonly(),
  'totalTokens': z.number().readonly(),
  'cacheReadTokens': z.number().readonly().optional(),
  'cacheWriteTokens': z.number().readonly().optional(),
  'provider': z.string().readonly().optional(),
  'model': z.string().readonly().optional(),
})).readonly(),
  'issues': z.array(z.object({
  'kind': z.union([z.literal("unreadable-session"), z.literal("missing-turn"), z.literal("unattributed-turn")]).readonly(),
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'projectId': z.string().readonly().optional(),
  'at': z.number().readonly().optional(),
})).readonly(),
  'unreadableSessions': z.number().readonly(),
}))

export const TYPERT = {
  package: '@deepseek-ai/dsh-client-ui-usage',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-client-ui-usage#usageStatistics/progress',
      service: 'usageStatistics',
      namespace: 'usageStatistics',
      method: 'progress',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-client-ui-usage/types#UsageProgress',
        create: _deepseek_ai_dsh_client_ui_usage_usageStatistics_progress_result$schema,
      },
      sourceLocation: {"file":"packages/client/ui-usage/src/index.ts","line":50,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-client-ui-usage#usageStatistics/snapshot',
      service: 'usageStatistics',
      namespace: 'usageStatistics',
      method: 'snapshot',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'force',
          wire: 'force',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-client-ui-usage#usageStatistics/snapshot:force',
            create: _deepseek_ai_dsh_client_ui_usage_usageStatistics_snapshot_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-client-ui-usage/types#UsageSnapshot',
        create: _deepseek_ai_dsh_client_ui_usage_usageStatistics_snapshot_result$schema,
      },
      sourceLocation: {"file":"packages/client/ui-usage/src/index.ts","line":59,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "Reads complete, live-preferred logs without activating their agents.",
        "summary": "Reads complete, live-preferred logs without activating their agents.",
        "tags": [],
        "jsDoc": "/** Reads complete, live-preferred logs without activating their agents. */",
        "key": "usageStatistics",
        "exportName": "default",
        "members": [
          {
            "kind": "method",
            "name": "progress",
            "signature": "@Remote('progress') progress(): UsageProgress",
            "summary": "Read the current observation's progress.",
            "jsDoc": "/** Read the current observation's progress. @returns processed and total session counts. */"
          },
          {
            "kind": "method",
            "name": "snapshot",
            "signature": "@Remote('snapshot') async snapshot(force: boolean): Promise<UsageSnapshot>",
            "summary": "Read provider-reported token totals for completed turns in each logical session.",
            "jsDoc": "/**\n * Read provider-reported token totals for completed turns in each logical session.\n * Fork-inherited events are excluded so they are counted only in their source session.\n * @param force - recompute every session even when its current process revision matches.\n * @returns session, project, token, and quality facts for the dashboard.\n */"
          }
        ],
        "types": [
          {
            "name": "Branded",
            "declaration": "export type Branded<B extends string> = string & { readonly [BRAND]: B; };"
          },
          {
            "name": "SessionId",
            "declaration": "export type SessionId = Branded<'SessionId'>;"
          },
          {
            "name": "UsageIssue",
            "declaration": "export interface UsageIssue {\n    readonly kind: 'unreadable-session' | 'missing-turn' | 'unattributed-turn';\n    readonly sessionId: SessionId;\n    readonly title: string;\n    readonly projectId?: string;\n    readonly at?: number;\n}"
          },
          {
            "name": "UsageProgress",
            "declaration": "export interface UsageProgress {\n    readonly completed: number;\n    readonly total: number;\n    readonly running: boolean;\n}"
          },
          {
            "name": "UsageProject",
            "declaration": "export interface UsageProject {\n    readonly id: string;\n    readonly title: string;\n}"
          },
          {
            "name": "UsageRecord",
            "declaration": "export interface UsageRecord {\n    readonly sessionId: SessionId;\n    readonly at: number;\n    readonly inputTokens: number;\n    readonly outputTokens: number;\n    readonly totalTokens: number;\n    readonly cacheReadTokens?: number;\n    readonly cacheWriteTokens?: number;\n    readonly provider?: string;\n    readonly model?: string;\n}"
          },
          {
            "name": "UsageSession",
            "declaration": "export interface UsageSession {\n    readonly id: SessionId;\n    readonly title: string;\n    readonly projectId?: string;\n    readonly lastAt: number;\n    readonly missingTurns: number;\n}"
          },
          {
            "name": "UsageSnapshot",
            "declaration": "export interface UsageSnapshot {\n    readonly capturedAt: number;\n    readonly projects: readonly UsageProject[];\n    readonly sessions: readonly UsageSession[];\n    readonly records: readonly UsageRecord[];\n    readonly issues: readonly UsageIssue[];\n    readonly unreadableSessions: number;\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
